version: '3'
services:
  juice-shop:
    image: vsemenok/juiceshop
    ports:
      - 3000:3000
    networks:
      - frontend
  bodgeit:
    image: securecodebox/bodgeit
    ports:
      - 8081:8080
    networks:
      - frontend
